#!/bin/bash
# Wrapper script to startup CpnetSocketServer on Linux, possibly MAC

CLASS=CpnetSocketServer
JAR1=${CLASS}.jar	# location of the server JAR

if [[ ! -f ${JAR1} ]]; then
	echo "Missing: ${JAR1}" >&2
	exit 1
fi

/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp ${JAR1} ${CLASS} "${@}"

